Imports System.Data.SqlClient

Public Class ASCSQLS2
    Public Shared sqlServerConnection As New SqlConnection
    Public Shared sqlServerCommand As New SqlCommand
    Public Shared sqlServerSql As String = String.Empty
    Public Shared sqlServerDst As New DataSet()
    Public Shared sqlServerTransaction As SqlTransaction

    Public Shared TDAs As New Dictionary(Of String, SqlDataAdapter)
    Public Shared TBLs As New Dictionary(Of String, DataTable)
    Public Shared pROWs As New Dictionary(Of String, DataRow)
    Public Shared ROWs As New Dictionary(Of String, DataRow)
    Public Shared CMDs As New Dictionary(Of String, SqlCommand)
    Private Shared temps As New List(Of Integer)


    ''' <summary>
    ''' Begin a SQL Server Transaction
    ''' </summary>
    ''' <remarks></remarks>
    Public Shared Sub sqlServerBeginTrans()
        sqlServerTransaction = sqlServerConnection.BeginTransaction
        sqlServerCommand.Transaction = sqlServerTransaction
    End Sub

    ''' <summary>
    ''' Commit a SQL Server Trans Action
    ''' </summary>
    ''' <remarks></remarks>
    Public Shared Sub sqlServerCommitTrans()
        sqlServerTransaction.Commit()
    End Sub

    ''' <summary>
    ''' Rollback a SQL Server Transaction
    ''' </summary>
    ''' <remarks></remarks>
    Public Shared Sub sqlServerRollback()
        sqlServerTransaction.Rollback()
    End Sub

    ''' <summary>
    ''' Creates a DataAdapter which will be used to Fill and optionally to Update data.
    ''' </summary>
    ''' <param name="tbl">The DataTable used to contain the Data on the Client.</param>
    ''' <param name="TABLE_NAME">A logical name for the DataTable.  This should be the TABLE_NAME in the Database for Adapters which are used for Updates.</param>
    ''' <param name="sql_custom">The SQL statement used to generate the Result Set for the Select Statement.  If "*", then all columns are used.  If "**" then ASCMAIN1.sql is used for the result set, but the Insert and Update statements will be prepared using * from the TABLE_NAME</param>
    ''' <param name="NumberOfKeysUsedToSelect"></param>
    ''' <param name="for_update">Set this to True to cause the Insert/Update/Delete statements to be generated for the Adapter.  A Valid (Database) TABLE_NAME must be specified when this field is set (or defaulted) to True</param>
    ''' <param name="custom_parameters">A string indicating the number and types of parameters used in the where clause, such as "VVIND" to indicate 5 parameters, 2 Varchar2, 1 Integer, 1 Number, and 1 Date.  Always use :PARMx as your parameter names in the where clause.</param>
    ''' <param name="Key_Field_Count">The number of leading columns that are to be used to create a key for the DataTable generated by the Fill.  This field is only necessary when specifying a Read-Only Result Set.</param>
    ''' <remarks></remarks>
    Public Shared Sub sqlSvrCreate_TDA( _
    ByRef tbl As DataTable, _
    ByVal TABLE_NAME As String, _
    ByVal sql_custom As String, _
    Optional ByVal NumberOfKeysUsedToSelect As Integer = -1, _
    Optional ByVal for_update As Boolean = True, _
    Optional ByVal custom_parameters As String = "", _
    Optional ByVal Key_Field_Count As Integer = -1, _
    Optional ByVal Update_COLUMN_NAMEs As String = "")

        Dim tblTABLE_NAME As String = TABLE_NAME
        If Not tbl.TableName Like "Table*" Then
            tblTABLE_NAME = tbl.TableName
        End If

        TDAs.Add(tblTABLE_NAME, ASCSQLS1.sqlSvrGetDataAdapter(tbl, TABLE_NAME, sql_custom, for_update, Key_Field_Count, False, NumberOfKeysUsedToSelect, Update_COLUMN_NAMEs, custom_parameters, tblTABLE_NAME))
        'If custom_parameters.Length <> 0 Then '  <> "" Then
        '    Dim ptbl As New DataTable
        '    Call ascsqls1.Create_Parameters(TDAs(tblTABLE_NAME).SelectCommand, custom_parameters, ptbl)
        '    pROWs.Add(tblTABLE_NAME, ptbl.NewRow)
        'End If
        'Dim tbl_schema As DataTable
        'Using rdr = TDAs(tblTABLE_NAME).SelectCommand.ExecuteReader

        '    tbl_schema = rdr.GetSchemaTable
        '    tbl_schema.PrimaryKey = New DataColumn() {tbl_schema.Columns("ColumnName")}

        '    TBL_SCHEMAs.Add(tblTABLE_NAME, tbl_schema)
        'End Using
        For Each dc As DataColumn In tbl.Columns
            'Dim row_Schema As DataRow = tbl_Schema.Rows.Find(dc.ColumnName)
            'If Not row_Schema("NumericPrecision").Equals(DBNull.Value) Then
            '    If Val(row_Schema("NumericScale")) = 0 Then
            '        'dc.DataType = GetType(System.Int64)
            '    Else
            '        'dc.DataType = GetType(System.Decimal)
            '    End If
            'End If
            dc.ReadOnly = False
        Next

        TBLs.Add(tblTABLE_NAME, tbl)
        Dim dvw As New DataView(tbl)
        'DVWs.Add(tblTABLE_NAME, dvw)
    End Sub

    ''' <summary>
    ''' Performs the Update Command for the Table Data Adapter.  Use sql_Delete only if you want to delete rows (using the supplied sql_Delete statement) and then have the current rows Inserted.
    ''' </summary>
    ''' <param name="TABLE_NAME"></param>
    ''' <param name="sql_Delete">Specify a complete Delete statement, or else just the where clause.  If sql_delete does not begin with the word 'Delete', then the clause 'Delete from {TABLE_NAME} where ' will be pre-pended to the clause supplied.</param>
    ''' <remarks></remarks>
    Shared Sub sqlSvrUpdate_Record_TDA(ByVal TABLE_NAME As String, Optional ByVal sql_Delete As String = "")

        ' Without the next 2 lines, data in text boxes in single row datatables (like header tables) will not get written to Oracle
        'Dim X As CurrencyManager = Me.BindingContext(dst.Tables(TABLE_NAME))
        'X.EndCurrentEdit()

        'If AUDIT.ContainsKey(TABLE_NAME) Then
        '    WriteAuditTrail(TABLE_NAME)
        'End If

        If sql_Delete <> "" Then
            If Mid(Trim(sql_Delete), 1, 6).ToUpper <> "DELETE" Then
                sql_Delete = "Delete from " & TABLE_NAME & " where " & sql_Delete
            End If
            ASCSQLS1.sqlSvrExecuteSQL(sql_Delete)
            TBLs(TABLE_NAME).AcceptChanges()
            For Each row As DataRow In TBLs(TABLE_NAME).Rows
                row.SetAdded()
            Next
        Else
        End If
        TDAs(TABLE_NAME).Update(sqlServerDst.Tables(TABLE_NAME))
    End Sub

    Shared Function sqlSvrFill_Records( _
    ByVal TABLE_NAME As String, _
    ByVal KEY_VALUE As String, _
    Optional ByVal ClearBeforeFilling As Boolean = True, _
    Optional ByVal Temp_Select As String = "", _
    Optional ByVal tblSubstitute As DataTable = Nothing) As Integer

        If KEY_VALUE = "" Then
            Return sqlSvrFill_Records(TABLE_NAME, , ClearBeforeFilling, Temp_Select, tblSubstitute)
        Else
            Return sqlSvrFill_Records(TABLE_NAME, New String() {KEY_VALUE}, ClearBeforeFilling, Temp_Select, tblSubstitute)
        End If

    End Function

    Public Shared Function sqlSvrFill_Records( _
    ByVal TABLE_NAME As String, _
    Optional ByVal Parameters() As Object = Nothing, _
    Optional ByVal ClearBeforeFilling As Boolean = True, _
    Optional ByVal Temp_Select As String = "", _
    Optional ByVal tblSubstitute As DataTable = Nothing) As Integer

        Dim tbl As DataTable
        If tblSubstitute Is Nothing Then
            tbl = TBLs(TABLE_NAME)
        Else
            tbl = tblSubstitute
        End If

        If Not TDAs.ContainsKey(TABLE_NAME) Then
            Stop ' SHOULD RAISE AN ERROR
        Else

            If ClearBeforeFilling Then
                'dst.Tables(TABLE_NAME).Rows.Clear()
                'TBLs(TABLE_NAME).Rows.Clear()
                tbl.Rows.Clear()
            End If

            Dim UseRow As Boolean = False ' we need to know how to autodetect when to use this

            If UseRow Then
                For i As Integer = 0 To pROWs(TABLE_NAME).ItemArray.Length - 1
                    TDAs(TABLE_NAME).SelectCommand.Parameters(i).Value = pROWs(TABLE_NAME).Item(i)
                Next
            Else
                With TDAs(TABLE_NAME).SelectCommand
                    If Parameters IsNot Nothing Then
                        For i As Integer = 0 To UBound(Parameters)
                            .Parameters(i).Value = Parameters(i)
                        Next
                    Else
                        For i As Integer = 0 To .Parameters.Count - 1
                            .Parameters(i).Value = System.DBNull.Value
                        Next
                    End If
                End With
            End If

            Dim SelectCommandSQL As String = ""
            If Temp_Select <> "" Then
                SelectCommandSQL = TDAs(TABLE_NAME).SelectCommand.CommandText
                TDAs(TABLE_NAME).SelectCommand.CommandText = Temp_Select
            End If

            'Fill_Records = TDAs(TABLE_NAME).Fill(TBLs(TABLE_NAME))

            Dim XDT As Date = Now

            sqlSvrFill_Records = TDAs(TABLE_NAME).Fill(tbl)

            If Temp_Select <> "" Then
                TDAs(TABLE_NAME).SelectCommand.CommandText = SelectCommandSQL
            End If
        End If
    End Function

    Public Shared Function sqlSvrLookUp( _
    ByVal TABLE_NAME As String, _
    ByVal KEY() As String, _
    Optional ByVal Return_Empty_Row_if_Missing As Boolean = False) As DataRow

        Dim row As DataRow = Nothing

        If Not ROWs.ContainsKey(TABLE_NAME) Then
            Call sqlSvrCreate_Lookup(TABLE_NAME)
        End If

        ROWs(TABLE_NAME).Table.Rows.Clear()

        With CMDs(TABLE_NAME)
            For i As Integer = 0 To UBound(KEY)
                .Parameters(i).Value = KEY(i)
            Next

            Using rdr As SqlDataReader = .ExecuteReader
                If rdr.HasRows Then
                    rdr.Read()
                    row = ROWs(TABLE_NAME).Table.NewRow
                    'row = TBLs(TABLE_NAME).NewRow
                    For i As Integer = 0 To rdr.FieldCount - 1
                        row.Item(i) = rdr.Item(i)
                    Next
                Else
                    If Return_Empty_Row_if_Missing Then
                        'Stop
                        row = ROWs(TABLE_NAME).Table.NewRow
                        If ROWs(TABLE_NAME).Table.PrimaryKey.Length = KEY.Length Then
                            For i As Integer = 0 To UBound(KEY)
                                row.Item(i) = KEY(i)
                            Next
                        End If
                    End If
                End If
            End Using
        End With

        If row IsNot Nothing Then
            ROWs(TABLE_NAME) = row
        End If
        Return row
    End Function

    Public Shared Function sqlSvrLookUp( _
    ByVal TABLE_NAME As String, _
    ByVal KEY As String, _
    Optional ByVal Return_Empty_Row_if_Missing As Boolean = False) As DataRow
        Return sqlSvrLookUp(TABLE_NAME, New String() {KEY}, Return_Empty_Row_if_Missing)
    End Function

    Public Shared Sub sqlSvrCreate_Lookup( _
    ByVal LOOKUP_NAME As String, _
    Optional ByVal column_list As String = "*", _
    Optional ByVal where_clause As String = "", _
    Optional ByVal custom_parameters As String = "", _
    Optional ByVal create_parameters_for_key As Boolean = True)

        ' Examples of usage:
        'Create_Lookup("GLTACCT1")
        'Create_Lookup("POTORDR1.OPEN", , "PO_STATUS_CODE = 'O' and PO_ORDER_TYPE = 'S'")
        'Create_Lookup("ICTPRCAT", , "PROD_CODE in (Select Distinct PROD_CODE from ICTPROD1 where VEND_CODE = :PARM1)", "V")
        'Create_Lookup("ICTITEM1.ITEM_UPC_CODE", , "ITEM_UPC_CODE = :PARM1", "V", False)

        Dim TABLE_NAME As String = LOOKUP_NAME
        If InStr(TABLE_NAME, ".") <> 0 Then
            TABLE_NAME = Split(TABLE_NAME, ".")(0)
        End If

        Dim tbl As DataTable

        If column_list = "" Or column_list = "*" Then
            tbl = ASCSQLS1.sqlSvrGetDataTable("*", TABLE_NAME, -1, False)
        Else
            sqlServerSql = "Select " & column_list & " from " & TABLE_NAME
            tbl = ASCSQLS1.sqlSvrGetDataTable("", TABLE_NAME, -1, False)
        End If
        'tbl.TableName = LOOKUP_NAME ?

        Dim cmd As SqlCommand = sqlServerConnection.CreateCommand
        Dim sql As String = ""
        If create_parameters_for_key Then
            For Each dc As DataColumn In tbl.PrimaryKey
                Dim COLUMN_NAME As String = dc.ColumnName
                sql = sql & " and (" & COLUMN_NAME & " = @S_" & COLUMN_NAME & ")"
                Select Case dc.DataType.Name
                    Case "String", "Int16", "Int32"
                        cmd.Parameters.Add("S_" & COLUMN_NAME, SqlDbType.VarChar)
                    Case Else
                        Stop
                End Select
            Next
        End If

        If custom_parameters <> "" Then Call ASCSQLS1.sqlSvrCreate_Parameters(cmd, custom_parameters)

        If where_clause <> "" Then
            where_clause = " and " & where_clause
        End If
        cmd.CommandText = "Select * from " & TABLE_NAME & sqlSvrSQL_Add_WHERE(sql & where_clause)

        If CMDs.ContainsKey(LOOKUP_NAME) Then
            CMDs.Remove(LOOKUP_NAME)
        End If
        CMDs.Add(LOOKUP_NAME, cmd)
        If ROWs.ContainsKey(LOOKUP_NAME) Then
            ROWs.Remove(LOOKUP_NAME)
        End If
        ROWs.Add(LOOKUP_NAME, tbl.NewRow)
    End Sub

    Public Shared Function sqlSvrSQL_Add_WHERE(ByVal WHEREless_Clause As String) As String
        Dim z As String
        z = LTrim$(WHEREless_Clause)
        If InStr(UCase$(z), "WHERE") = 1 Then
            sqlSvrSQL_Add_WHERE = z
        ElseIf InStr(UCase$(z), "AND") = 1 Then
            sqlSvrSQL_Add_WHERE = " where " & Mid$(z, 4)
        ElseIf z <> "" Then
            sqlSvrSQL_Add_WHERE = " where " & z
        Else
            sqlSvrSQL_Add_WHERE = WHEREless_Clause
        End If
    End Function

    Public Shared Sub sqlSvrResetState()
        sqlServerDst.Reset()
        TDAs.Clear()
        TBLs.Clear()
        'TBL_SCHEMAs.Clear()
        ROWs.Clear()
        'DVWs.Clear()
        pROWs.Clear()
        temps.Clear()
    End Sub

    Public Shared Function sqlSvrTemp_Table( _
        Optional ByVal sql As String = "", _
        Optional ByVal FORM_NAME As String = "", _
        Optional ByVal XNO As String = "", _
        Optional ByVal custom_parameters As String = "", _
        Optional ByVal PARMs() As String = Nothing) As String

        If sql = "" Then
            sql = sqlServerSql
        End If

        'Try
        '    If FORM_NAME = "" Then FORM_NAME = ASCMAIN1.ActiveForm.MENU_ITEM_OBJECT
        '    If XNO = "" Then XNO = ASCMAIN1.ActiveForm.XNO
        'Catch ex As Exception
        'End Try


        Dim TABLE_NAME As String = "ASW" & sqlSvrNext_Control_No("TEMP_NO")
        'Dim sqlASTTEMP1 As String = "Insert into ASTTEMP1 Values ('" & TABLE_NAME & "','" & SESSION_NO & "',sysdate,'" & USER_ID & "','" & FORM_NAME & "','" & XNO & "'," & CStr(DBS_SESSION_ID) & ")"
        'ascsqls1.ExecuteSQL(sqlASTTEMP1)
        Dim insertAt = sql.ToUpper.IndexOf("FROM")

        If insertAt > 0 Then sql = sql.Insert(insertAt, "INTO " & TABLE_NAME & " ")
        sql = sql '& " INTO " & TABLE_NAME '"Create Table " & TABLE_NAME & " as " & sql
        If custom_parameters = "" Then
            ASCSQLS1.sqlSvrExecuteSQL(sql)
        Else
            ASCSQLS1.sqlSvrExecuteSQL(sql, custom_parameters, PARMs)
        End If
        Return TABLE_NAME
    End Function

    Public Shared Function sqlSvrNext_Control_No( _
    ByVal CTL_NO_TYPE As String, _
    Optional ByVal How_Many As Long = 1) As String

        Dim CTL_NO_LAST As Long
        Dim CTL_NO_LENGTH As Integer

        Dim tblTATCTLN1 As New DataTable
        'Dim sql As String = "Select * from TATCTLN1 where CTL_NO_TYPE = '" & CTL_NO_TYPE & "'"
        Dim sql As String = "Select * from abs_TATCTLN1 (UPDLOCK) where CTL_NO_TYPE = '" & CTL_NO_TYPE & "'"
        Dim sqlAda As SqlDataAdapter = ASCSQLS1.sqlSvrGetDataAdapter(tblTATCTLN1, "abs_TATCTLN1", sql, True)

        Dim rowTATCTLN1 As DataRow
        If tblTATCTLN1.Rows.Count = 0 Then
            rowTATCTLN1 = tblTATCTLN1.NewRow()
            rowTATCTLN1.Item("CTL_NO_TYPE") = CTL_NO_TYPE
            rowTATCTLN1.Item("CTL_NO_LAST") = 0
            tblTATCTLN1.Rows.Add(rowTATCTLN1)
        Else
            rowTATCTLN1 = tblTATCTLN1.Rows(0)
        End If

        CTL_NO_LENGTH = Val(rowTATCTLN1.Item("CTL_NO_LENGTH") & "")
        If CTL_NO_LENGTH = 0 Then
            'If InStr(CTL_NO_TYPE, ".") <> 0 Then
            '    Dim sqlCTL_NO_LENGTH As String = "Select DATA_LENGTH from USER_TAB_COLUMNS where TABLE_NAME = '" & Split(CTL_NO_TYPE, ".")(0) & "' and COLUMN_NAME = '" & Split(CTL_NO_TYPE, ".")(1) & "'"
            '    CTL_NO_LENGTH = Val(ascsqls1.GetDataValue(sqlCTL_NO_LENGTH) & "")
            'End If
            If CTL_NO_LENGTH = 0 Then
                CTL_NO_LENGTH = 10
            End If
            rowTATCTLN1.Item("CTL_NO_LENGTH") = CTL_NO_LENGTH
        End If

        If How_Many <= 0 Then
            How_Many = 1
        End If

        CTL_NO_LAST = Val(rowTATCTLN1.Item("CTL_NO_LAST") & "") + 1

        If CTL_NO_LAST >= 10 ^ CTL_NO_LENGTH Then
            CTL_NO_LAST = 1
        End If

        sqlSvrNext_Control_No = Format$(CTL_NO_LAST, "".PadLeft(CTL_NO_LENGTH, "0"))
        CTL_NO_LAST = CTL_NO_LAST + How_Many - 1
        If CTL_NO_LAST >= 10 ^ CTL_NO_LENGTH Then
            CTL_NO_LAST = CTL_NO_LAST - 10 ^ CTL_NO_LENGTH + 1
        End If
        rowTATCTLN1.Item("CTL_NO_LAST") = CTL_NO_LAST
        Dim SUCCESS As Integer = sqlAda.Update(tblTATCTLN1)

        'sqlAda.Dispose()
        'sqlAda = Nothing

    End Function

    Shared Sub sqlSvrEnforceConstraints(Optional ByVal enforce As Boolean = True) 'As String
        Dim hasConstraintErrors As Boolean = False

        Try
            sqlServerDst.EnforceConstraints = enforce
        Catch ex As ConstraintException
            hasConstraintErrors = True
        End Try

        If Not hasConstraintErrors Then
            'Return ""
        End If

    End Sub

End Class
